//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPal_Invoiceing.EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customerInvoice
    {
        public long idtbl_customerInvoice { get; set; }
        public string customerName { get; set; }
        public string customerEmail { get; set; }
        public double amount { get; set; }
        public Nullable<System.DateTime> System_Date { get; set; }
    }
}
